version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
  # populate:
  #     image: ubuntu:16.04
  #     command: scripts/populate.py
      # working_dir: /src
      # links:
      #     - elasticsearch:elasticsearch
      # volumes:
      #     - .:/src
      # environment:
      #     - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://elastic:9200/_cat/health?h=st) = 200 ]
      #     - WAIT_START_CMD=python scripts/populate.py
      #     - WAIT_SLEEP=2
      #     - WAIT_LOOPS=10
  populate:
    build:
      context: .
      dockerfile: Dockerfile-es
      args:
        buildno: 1
    depends_on:
    - elasticsearch
