FROM ubuntu:16.04
MAINTAINER Ryan Stonebraker

RUN apt-get update
RUN apt-get install -y python3 python3-pip sed

RUN mkdir /var/www
COPY scripts/requirements.txt /var/www
WORKDIR /var/www
RUN pip3 install -r requirements.txt

COPY . /var/www
WORKDIR /var/www

ENTRYPOINT ["./entrypoint.sh"]
